# -*- coding: utf-8 -*-
"""10/4_4110E008.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jd7_nYExN6XxUotMHYO-zRSvwzIup969
"""

a = 33
b = 200

if b > a:
  print("b is greater than a")

a = 32
b = 33

if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

a = 33
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

a = 200
b = 33

if b > a:
  print("b is greater than a")
else:
  print("b is not greater than a")

a = 200
b = 33

if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

year= eval(input("請輸入年"))

if ((year%400==0) or (year%4==0 and year%100!=0)):
  print("{0} 是閏年".format(year))
else:
  print("{0} 不是閏年".format(year))

list1=range(10)
print(list1)

print(list(list1))

list2=range(-4,5)
print(list(list2))

list3=range(-4,5,2)
print(list(list3))

for n in range(5):
  print(n)

for n in range(10):
    print(n, end='@')

mysum = 0

for n in range(5):
  mysum += n
  print(mysum)

x = int(input("請輸入一個正整數:"))

mysum = 0

for n in range(x+1): 
  mysum += n

print(mysum)

numbers = [21, 4, 35, 1, 8, 7, 3, 6, 9]
my_numbers = []

for number in numbers:
  if (number % 2 != 0): 
    my_numbers.append(number)

print(my_numbers)

total = i = 1

n = int(input("請輸入正整數 n 的值：")) 

while(i<=n):
    total *= i  
    i+=1      

print("%d!=%d" % (n, total))

fruits = ["香蕉","蘋果","橘子","鳳梨","草莓"]

while True:
    fruit = input("請輸入喜歡的水果(Enter 結束)：")

  # 要執行程式請記得把底下兩行 # 去除 
  #  if (fruit==""):
  #      break

    n = fruits.count(fruit) 
    if (n>0):  # 串列元素存在
        p=fruits.index(fruit)
        print("%s 在串列中的第 %d 項" %(fruit,p+1))
    else:
        print(fruit,"不在串列中!")

n = int(input("請輸入正整數："))

for i in range(1, n+1):
    if i % 5 ==0:
        continue
    print(i,end=" ")

#!/usr/bin/python
# -*- coding: UTF-8 -*-
 
for i in range(1,6):
    for j in range(1,5):
        for k in range(1,7):
            if( i != k ) and (i != j) and (j != k):
                print(i,j,k)

#!/usr/bin/python
# -*- coding: UTF-8 -*-
 
def swap(a,b):
    a,b = b,a
    return (a,b)
 
if __name__ == '__main__':
    x = 10
    y = 20
    print('x = %d,y = %d' % (x,y))
    x,y = swap(x,y)
    print('x = %d,y = %d' % (x,y))

x = 111

def f1():
    x = 222
    print(x) 

f1()
print(x)

x = 1

def increase():
    global x
    x =  x + 1
    print(x) 

increase()
print(x)
increase()
increase()
print(x)